"""Add relationships to models

Revision ID: 61492d684142
Revises: c2c340fbe989
Create Date: 2025-09-14 20:57:21.334036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61492d684142'
down_revision: Union[str, Sequence[str], None] = 'c2c340fbe989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False, default='general'))
    
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_data', sa.Text(), nullable=True))
    
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_data', sa.Text(), nullable=True))
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_student', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_verified_student', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.String(length=50), nullable=True))
        # SQLite doesn't support unique constraints in ALTER TABLE, so we'll handle this in application code
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('student_id')
        batch_op.drop_column('school')
        batch_op.drop_column('is_verified_student')
        batch_op.drop_column('is_student')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
    
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('ticket_data')
    
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_column('invitation_data')
    
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('category')
    # ### end Alembic commands ###
